### ISSUE TITLE
Initializing Hydra here may cause problems for downstream repos using Hydra

### ISSUE THREAD

**Issue by alexrgilbert** [sensorium-competition/experanto#48]
https://github.com/sensorium-competition/experanto/blob/ba0133153247c27eafe16778c6a2051bf01a8768/experanto/configs.py#L4

When using Experanto data loaders in downstream repos using Hydra, instantiating Hydra in Experanto (used to build default configurations) seems to cause issues:

`Traceback (most recent call last):
  File "/home/alexrgilbert/.virtualenvs/fm/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/alexrgilbert/dev/foundation-models-reference-hydra-2/foundation_models/lightning/mtm/__init__.py", line 1, in <module>
    from foundation_models.lightning.mtm.datamodule import ExperantoDataModule
  File "/home/alexrgilbert/dev/foundation-models-reference-hydra-2/foundation_models/lightning/mtm/datamodule.py", line 8, in <module>
    from experanto.utils import LongCycler
  File "/home/alexrgilbert/dev/foundation-models-reference-hydra-2/context/experanto/experanto/__init__.py", line 1, in <module>
    from .experiment import Experiment
  File "/home/alexrgilbert/dev/foundation-models-reference-hydra-2/context/experanto/experanto/experiment.py", line 12, in <module>
    from .configs import DEFAULT_MODALITY_CONFIG
  File "/home/alexrgilbert/dev/foundation-models-reference-hydra-2/context/experanto/experanto/configs.py", line 4, in <module>
    with initialize(version_base=None, config_path="../configs/", ):
  File "/home/alexrgilbert/.virtualenvs/fm/lib/python3.10/site-packages/hydra/initialize.py", line 91, in __init__
    Hydra.create_main_hydra_file_or_module(
  File "/home/alexrgilbert/.virtualenvs/fm/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 53, in create_main_hydra_file_or_module
    return Hydra.create_main_hydra2(job_name, config_search_path)
  File "/home/alexrgilbert/.virtualenvs/fm/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 68, in create_main_hydra2
    GlobalHydra.instance().initialize(hydra)
  File "/home/alexrgilbert/.virtualenvs/fm/lib/python3.10/site-packages/hydra/core/global_hydra.py", line 16, in initialize
    raise ValueError(
ValueError: GlobalHydra is already initialized, call GlobalHydra.instance().clear() if you want to re-initialize`

Could possibly fix by calling `GlobalHydra.instance().clear()`, but not sure if this would clear things from the existing hydra state that we want to keep. I think we should remove the import of DEFAULT*CONFIG's in other modules and make the corresponding arguments required, so if someone wants to explicitly import the config they can, otherwise they can fill in there own config in those .

**Comment by pollytur** [comment]
@KonstantinWilleke I guess it is now fixed in the PR from the filter branch. Is it correct? If yes, could we close this issue?

**Comment by KonstantinWilleke** [comment]
Yes, this issue is resolved and can be closed.
